[package]
name = "deser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.193"
serde_plain = "1.0.2"
unicode-segmentation = "1.10.1"
