[package]
name = "deser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
rstest = "0.18.2"
serde = "1.0.193"
serde_plain = "1.0.2"
